### ISSUE TITLE
WowUp not regonizing it as valid tBC Addon

### ISSUE THREAD

**Issue by Fawenah** [Crablicious/SlamDelay#1]
WowUp does not recognize it as a valid addon to track, as it is missing a "*-bc.zip" in a tagged release

![WowUp Error](https://user-images.githubusercontent.com/15831364/141352296-2d6c9ea0-b251-474a-adf2-d013a2e59f8a.png)

**Comment by Crablicious** [comment]
I made a new release today that is named similar to other addons with <name>-<version>-bcc.zip.
Works to install to my TBC Classic through WoWUp (never used it before so hopefully I did it right)
